# CMakeLists.txt 

#Include Google Test 
include_directories(\\wsl.localhost\Ubuntu-22.04\home\sething2002\googletest\build\include)
target_link_libraries(/home/sething2002/2024_UoA/s1/s1-2024-ADDS \\wsl.localhost\Ubuntu-22.04\home\sething2002\googletest\build\lib\libgtest.a \\wsl.localhost\Ubuntu-22.04\home\sething2002\googletest\build\lib\libgtest_main.a)